import { defineConfig } from 'vite-plus';
import react from '@vitejs/plugin-react';
import path, { resolve } from 'path';
import tailwindcss from '@tailwindcss/vite';

const __dirname = path.dirname(new URL(import.meta.url).pathname);

export default defineConfig({
  lint: {
    ignorePatterns: ['dist', 'node_modules'],
    plugins: ['oxc', 'typescript', 'unicorn', 'react'],
    categories: {
      correctness: 'warn',
    },
    env: {
      builtin: true,
    },
    overrides: [
      {
        files: ['**/*.{ts,tsx}'],
        rules: {
          'constructor-super': 'off',
          'for-direction': 'error',
          'getter-return': 'off',
          'no-async-promise-executor': 'error',
          'no-case-declarations': 'error',
          'no-class-assign': 'off',
          'no-compare-neg-zero': 'error',
          'no-cond-assign': 'error',
          'no-const-assign': 'off',
          'no-constant-binary-expression': 'error',
          'no-constant-condition': 'error',
          'no-control-regex': 'error',
          'no-debugger': 'error',
          'no-delete-var': 'error',
          'no-dupe-class-members': 'off',
          'no-dupe-else-if': 'error',
          'no-dupe-keys': 'off',
          'no-duplicate-case': 'error',
          'no-empty': 'error',
          'no-empty-character-class': 'error',
          'no-empty-pattern': 'error',
          'no-empty-static-block': 'error',
          'no-ex-assign': 'error',
          'no-extra-boolean-cast': 'error',
          'no-fallthrough': 'error',
          'no-func-assign': 'off',
          'no-global-assign': 'error',
          'no-import-assign': 'off',
          'no-invalid-regexp': 'error',
          'no-irregular-whitespace': 'error',
          'no-loss-of-precision': 'error',
          'no-misleading-character-class': 'error',
          'no-new-native-nonconstructor': 'off',
          'no-nonoctal-decimal-escape': 'error',
          'no-obj-calls': 'off',
          'no-prototype-builtins': 'error',
          'no-redeclare': 'off',
          'no-regex-spaces': 'error',
          'no-self-assign': 'error',
          'no-setter-return': 'off',
          'no-shadow-restricted-names': 'error',
          'no-sparse-arrays': 'error',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unexpected-multiline': 'off',
          'no-unreachable': 'off',
          'no-unsafe-finally': 'error',
          'no-unsafe-negation': 'off',
          'no-unsafe-optional-chaining': 'error',
          'no-unused-labels': 'error',
          'no-unused-private-class-members': 'error',
          'no-unused-vars': 'error',
          'no-useless-backreference': 'error',
          'no-useless-catch': 'error',
          'no-useless-escape': 'error',
          'no-with': 'off',
          'require-yield': 'error',
          'use-isnan': 'error',
          'valid-typeof': 'error',
          'no-var': 'error',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error',
          'no-array-constructor': 'error',
          'no-unused-expressions': 'error',
          'typescript/ban-ts-comment': 'error',
          'typescript/no-duplicate-enum-values': 'error',
          'typescript/no-empty-object-type': 'error',
          'typescript/no-explicit-any': 'error',
          'typescript/no-extra-non-null-assertion': 'error',
          'typescript/no-misused-new': 'error',
          'typescript/no-namespace': 'error',
          'typescript/no-non-null-asserted-optional-chain': 'error',
          'typescript/no-require-imports': 'error',
          'typescript/no-this-alias': 'error',
          'typescript/no-unnecessary-type-constraint': 'error',
          'typescript/no-unsafe-declaration-merging': 'error',
          'typescript/no-unsafe-function-type': 'error',
          'typescript/no-wrapper-object-types': 'error',
          'typescript/prefer-as-const': 'error',
          'typescript/prefer-namespace-keyword': 'error',
          'typescript/triple-slash-reference': 'error',
          curly: 'off',
          '@stylistic/lines-around-comment': 'off',
          '@stylistic/max-len': 'off',
          '@stylistic/no-confusing-arrow': 'off',
          '@stylistic/no-mixed-operators': 'off',
          '@stylistic/no-tabs': 'off',
          '@stylistic/quotes': 'off',
          '@stylistic/js/lines-around-comment': 'off',
          '@stylistic/js/max-len': 'off',
          '@stylistic/js/no-confusing-arrow': 'off',
          '@stylistic/js/no-mixed-operators': 'off',
          '@stylistic/js/no-tabs': 'off',
          '@stylistic/js/quotes': 'off',
          '@stylistic/ts/lines-around-comment': 'off',
          '@stylistic/ts/quotes': 'off',
          'babel/quotes': 'off',
          '@babel/object-curly-spacing': 'off',
          '@babel/semi': 'off',
          '@stylistic/array-bracket-newline': 'off',
          '@stylistic/array-bracket-spacing': 'off',
          '@stylistic/array-element-newline': 'off',
          '@stylistic/arrow-parens': 'off',
          '@stylistic/arrow-spacing': 'off',
          '@stylistic/block-spacing': 'off',
          '@stylistic/brace-style': 'off',
          '@stylistic/comma-dangle': 'off',
          '@stylistic/comma-spacing': 'off',
          '@stylistic/comma-style': 'off',
          '@stylistic/computed-property-spacing': 'off',
          '@stylistic/dot-location': 'off',
          '@stylistic/eol-last': 'off',
          '@stylistic/func-call-spacing': 'off',
          '@stylistic/function-call-argument-newline': 'off',
          '@stylistic/function-call-spacing': 'off',
          '@stylistic/function-paren-newline': 'off',
          '@stylistic/generator-star-spacing': 'off',
          '@stylistic/implicit-arrow-linebreak': 'off',
          '@stylistic/indent': 'off',
          '@stylistic/jsx-quotes': 'off',
          '@stylistic/key-spacing': 'off',
          '@stylistic/keyword-spacing': 'off',
          '@stylistic/linebreak-style': 'off',
          '@stylistic/max-statements-per-line': 'off',
          '@stylistic/multiline-ternary': 'off',
          '@stylistic/new-parens': 'off',
          '@stylistic/newline-per-chained-call': 'off',
          '@stylistic/no-extra-parens': 'off',
          '@stylistic/no-extra-semi': 'off',
          '@stylistic/no-floating-decimal': 'off',
          '@stylistic/no-mixed-spaces-and-tabs': 'off',
          '@stylistic/no-multi-spaces': 'off',
          '@stylistic/no-multiple-empty-lines': 'off',
          '@stylistic/no-trailing-spaces': 'off',
          '@stylistic/no-whitespace-before-property': 'off',
          '@stylistic/nonblock-statement-body-position': 'off',
          '@stylistic/object-curly-newline': 'off',
          '@stylistic/object-curly-spacing': 'off',
          '@stylistic/object-property-newline': 'off',
          '@stylistic/one-var-declaration-per-line': 'off',
          '@stylistic/operator-linebreak': 'off',
          '@stylistic/padded-blocks': 'off',
          '@stylistic/quote-props': 'off',
          '@stylistic/rest-spread-spacing': 'off',
          '@stylistic/semi': 'off',
          '@stylistic/semi-spacing': 'off',
          '@stylistic/semi-style': 'off',
          '@stylistic/space-before-blocks': 'off',
          '@stylistic/space-before-function-paren': 'off',
          '@stylistic/space-in-parens': 'off',
          '@stylistic/space-infix-ops': 'off',
          '@stylistic/space-unary-ops': 'off',
          '@stylistic/switch-colon-spacing': 'off',
          '@stylistic/template-curly-spacing': 'off',
          '@stylistic/template-tag-spacing': 'off',
          '@stylistic/wrap-iife': 'off',
          '@stylistic/wrap-regex': 'off',
          '@stylistic/yield-star-spacing': 'off',
          '@stylistic/member-delimiter-style': 'off',
          '@stylistic/type-annotation-spacing': 'off',
          '@stylistic/jsx-child-element-spacing': 'off',
          '@stylistic/jsx-closing-bracket-location': 'off',
          '@stylistic/jsx-closing-tag-location': 'off',
          '@stylistic/jsx-curly-newline': 'off',
          '@stylistic/jsx-curly-spacing': 'off',
          '@stylistic/jsx-equals-spacing': 'off',
          '@stylistic/jsx-first-prop-new-line': 'off',
          '@stylistic/jsx-indent': 'off',
          '@stylistic/jsx-indent-props': 'off',
          '@stylistic/jsx-max-props-per-line': 'off',
          '@stylistic/jsx-newline': 'off',
          '@stylistic/jsx-one-expression-per-line': 'off',
          '@stylistic/jsx-props-no-multi-spaces': 'off',
          '@stylistic/jsx-tag-spacing': 'off',
          '@stylistic/jsx-wrap-multilines': 'off',
          '@stylistic/indent-binary-ops': 'off',
          '@stylistic/type-generic-spacing': 'off',
          '@stylistic/type-named-tuple-spacing': 'off',
          '@stylistic/js/array-bracket-newline': 'off',
          '@stylistic/js/array-bracket-spacing': 'off',
          '@stylistic/js/array-element-newline': 'off',
          '@stylistic/js/arrow-parens': 'off',
          '@stylistic/js/arrow-spacing': 'off',
          '@stylistic/js/block-spacing': 'off',
          '@stylistic/js/brace-style': 'off',
          '@stylistic/js/comma-dangle': 'off',
          '@stylistic/js/comma-spacing': 'off',
          '@stylistic/js/comma-style': 'off',
          '@stylistic/js/computed-property-spacing': 'off',
          '@stylistic/js/dot-location': 'off',
          '@stylistic/js/eol-last': 'off',
          '@stylistic/js/func-call-spacing': 'off',
          '@stylistic/js/function-call-argument-newline': 'off',
          '@stylistic/js/function-call-spacing': 'off',
          '@stylistic/js/function-paren-newline': 'off',
          '@stylistic/js/generator-star-spacing': 'off',
          '@stylistic/js/implicit-arrow-linebreak': 'off',
          '@stylistic/js/indent': 'off',
          '@stylistic/js/jsx-quotes': 'off',
          '@stylistic/js/key-spacing': 'off',
          '@stylistic/js/keyword-spacing': 'off',
          '@stylistic/js/linebreak-style': 'off',
          '@stylistic/js/max-statements-per-line': 'off',
          '@stylistic/js/multiline-ternary': 'off',
          '@stylistic/js/new-parens': 'off',
          '@stylistic/js/newline-per-chained-call': 'off',
          '@stylistic/js/no-extra-parens': 'off',
          '@stylistic/js/no-extra-semi': 'off',
          '@stylistic/js/no-floating-decimal': 'off',
          '@stylistic/js/no-mixed-spaces-and-tabs': 'off',
          '@stylistic/js/no-multi-spaces': 'off',
          '@stylistic/js/no-multiple-empty-lines': 'off',
          '@stylistic/js/no-trailing-spaces': 'off',
          '@stylistic/js/no-whitespace-before-property': 'off',
          '@stylistic/js/nonblock-statement-body-position': 'off',
          '@stylistic/js/object-curly-newline': 'off',
          '@stylistic/js/object-curly-spacing': 'off',
          '@stylistic/js/object-property-newline': 'off',
          '@stylistic/js/one-var-declaration-per-line': 'off',
          '@stylistic/js/operator-linebreak': 'off',
          '@stylistic/js/padded-blocks': 'off',
          '@stylistic/js/quote-props': 'off',
          '@stylistic/js/rest-spread-spacing': 'off',
          '@stylistic/js/semi': 'off',
          '@stylistic/js/semi-spacing': 'off',
          '@stylistic/js/semi-style': 'off',
          '@stylistic/js/space-before-blocks': 'off',
          '@stylistic/js/space-before-function-paren': 'off',
          '@stylistic/js/space-in-parens': 'off',
          '@stylistic/js/space-infix-ops': 'off',
          '@stylistic/js/space-unary-ops': 'off',
          '@stylistic/js/switch-colon-spacing': 'off',
          '@stylistic/js/template-curly-spacing': 'off',
          '@stylistic/js/template-tag-spacing': 'off',
          '@stylistic/js/wrap-iife': 'off',
          '@stylistic/js/wrap-regex': 'off',
          '@stylistic/js/yield-star-spacing': 'off',
          '@stylistic/ts/block-spacing': 'off',
          '@stylistic/ts/brace-style': 'off',
          '@stylistic/ts/comma-dangle': 'off',
          '@stylistic/ts/comma-spacing': 'off',
          '@stylistic/ts/func-call-spacing': 'off',
          '@stylistic/ts/function-call-spacing': 'off',
          '@stylistic/ts/indent': 'off',
          '@stylistic/ts/key-spacing': 'off',
          '@stylistic/ts/keyword-spacing': 'off',
          '@stylistic/ts/member-delimiter-style': 'off',
          '@stylistic/ts/no-extra-parens': 'off',
          '@stylistic/ts/no-extra-semi': 'off',
          '@stylistic/ts/object-curly-spacing': 'off',
          '@stylistic/ts/semi': 'off',
          '@stylistic/ts/space-before-blocks': 'off',
          '@stylistic/ts/space-before-function-paren': 'off',
          '@stylistic/ts/space-infix-ops': 'off',
          '@stylistic/ts/type-annotation-spacing': 'off',
          '@stylistic/jsx/jsx-child-element-spacing': 'off',
          '@stylistic/jsx/jsx-closing-bracket-location': 'off',
          '@stylistic/jsx/jsx-closing-tag-location': 'off',
          '@stylistic/jsx/jsx-curly-newline': 'off',
          '@stylistic/jsx/jsx-curly-spacing': 'off',
          '@stylistic/jsx/jsx-equals-spacing': 'off',
          '@stylistic/jsx/jsx-first-prop-new-line': 'off',
          '@stylistic/jsx/jsx-indent': 'off',
          '@stylistic/jsx/jsx-indent-props': 'off',
          '@stylistic/jsx/jsx-max-props-per-line': 'off',
          'babel/object-curly-spacing': 'off',
          'babel/semi': 'off',
          'flowtype/boolean-style': 'off',
          'flowtype/delimiter-dangle': 'off',
          'flowtype/generic-spacing': 'off',
          'flowtype/object-type-curly-spacing': 'off',
          'flowtype/object-type-delimiter': 'off',
          'flowtype/quotes': 'off',
          'flowtype/semi': 'off',
          'flowtype/space-after-type-colon': 'off',
          'flowtype/space-before-generic-bracket': 'off',
          'flowtype/space-before-type-colon': 'off',
          'flowtype/union-intersection-spacing': 'off',
          'standard/array-bracket-even-spacing': 'off',
          'standard/computed-property-even-spacing': 'off',
          'standard/object-curly-even-spacing': 'off',
          'unicorn/empty-brace-spaces': 'off',
          'unicorn/no-nested-ternary': 'off',
          'unicorn/number-literal-case': 'off',
          'react/jsx-curly-brace-presence': [
            'error',
            {
              props: 'never',
              children: 'never',
            },
          ],
          'react/rules-of-hooks': 'error',
          'react/exhaustive-deps': 'warn',
          'react/only-export-components': [
            'warn',
            {
              allowConstantExport: true,
            },
          ],
        },
        jsPlugins: [
          '@stylistic/eslint-plugin',
          '@stylistic/eslint-plugin-js',
          '@stylistic/eslint-plugin-ts',
          'eslint-plugin-babel',
          '@babel/eslint-plugin',
          '@stylistic/eslint-plugin-jsx',
          'eslint-plugin-flowtype',
          'eslint-plugin-standard',
        ],
        env: {
          es2020: true,
          browser: true,
        },
      },
    ],
    options: {},
  },
  fmt: {
    singleQuote: true,
    trailingComma: 'all',
    printWidth: 80,
    tabWidth: 2,
    arrowParens: 'avoid',
    semi: true,
    sortPackageJson: false,
    ignorePatterns: [],
  },
  pack: {
    entry: 'src/hook-table/index.ts',
    name: '@iff/react-hook-table',
    sourcemap: false,
    format: 'esm',
    minify: true,
    dts: {
      build: true,
    },
  },
  plugins: [
    react(
      /*{
      babel: {
        plugins: ['babel-plugin-react-compiler'],
      },
    }*/
    ),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
    },
  },
});
